### ISSUE TITLE
SEO url rewrite issue with .html ending

### ISSUE THREAD

**Issue by Kamik** [bcremer/shopware-with-nginx#11]
Wenn Ich in SEO/Router Einstellungen für Artikel folgende Template benutze - {sCategoryPath articleID=$sArticle.id}/{$sArticle.name}.html, nginx zeigt immer 404 Fehler. Das selbe mit Categorie-Template. Ohne .html funktioniert seo-rewrite ohne Probleme.

**Comment by bcremer** [comment]
Hi @Kamik,

the problem is the static files location: https://github.com/bcremer/shopware-with-nginx/blob/master/global/shopware.conf#L93

Just remove the `html` from the regex.

I'll try to find a nicer solution for that.

**Comment by bcremer** [comment]
You can also comment in this line: https://github.com/bcremer/shopware-with-nginx/blob/master/global/shopware.conf#L93

This enables a fallback to the shopware stack if a static file is not found.
