### ISSUE TITLE
robot.txt location in shopware.conf

### ISSUE THREAD

**Issue by Kamik** [bcremer/shopware-with-nginx#12]
Ich glaube sollte robot.txt location in shopware.conf auskommentiert sein, weil es ab Shopware 4  robot.txt über template erstellt wird. Oder entsprechende Hinweis dazu einfügen?

location = /robots.txt {
    allow all;
    log_not_found off;
    access_log off;
}

**Comment by bcremer** [comment]
This should be fixed with commit 001b30f5be0e0b1690d09d2ead4ce9cf02dfdf7b.
Thanks for reporting.
