### ISSUE TITLE
shopware.conf ---> robots.txt 

### ISSUE THREAD

**Issue by Winzigweich** [bcremer/shopware-with-nginx#19]
this entry works not with robots.txt --> error 404 with nginx.
## robots.txt support.

location = /robots.txt {
    log_not_found off;
    access_log off;
}

change it with...

location = /robots.txt {
    log_not_found off;
    access_log off;
    try_files $uri @shopware;
}

it works. ;-)

**Comment by larsbo** [comment]
I can confirm that the `try_files` directive is necessary.

**Comment by xf-** [comment]
@bcremer should be added since it is a nice core feature

**Comment by bcremer** [comment]
Closed by #26.
