### ISSUE TITLE
Plugin Rewrite Fehler

### ISSUE THREAD

**Issue by serviceHoster** [bcremer/shopware-with-nginx#2]
Es gibt aktuell ein Problem mit Plugins wie z.B. Actindo WaWi.
http://wiki.actindo.de/index.php?title=Shopware_4

Normal spricht man das Plugin mit www.domain.tdl/Actindo/ an.
Das Plugin kann man manuell unter www.domain.tdl/Actindo/xmlrpc_server.php?get_cryptmode=1&username=test bzw. www.domain.tdl/shopware.php/Actindo/xmlrpc_server.php?get_cryptmode=1&username=test aufrufen und hier kommt dann eine Antwort.

Bei Apache funktioniert dies problemlos, bei NGINX mit der .conf leider aktuell nicht.
Es kommt eine 404 ERROR.

Ich habe schon viel rumprobiert, leider komme ich nicht drauf woran es hier hängt.

// UPDATE:
Ich habe nun das Problem gefunden.
Da hier eine PHP Datei direkt aufgerufen werden muss, funktioniert location ~ .php$ { natürlich nicht, 
weil er nun direkt die PHP Datei xmlrpc..... aufrufen will und deshalb der 404 kommt.
Wenn ich location ~ shopware.php$ { schreibe funktioniert es nun korrekt.
Die Frage ist ob diese Korrektur nicht negative Auswirkungen auf die Basis Shopware Funktionen hat.

**Comment by macmastermike** [comment]
hallo
dieses problem habe ich jetzt auch... und nirgens eine lösung gefunden... ich habe jetzt schon einiges probiert in nginx aber nach wie vor keine funktionierende lösung gefunden...

**Comment by Kamik** [comment]
Wir haben Orgamax-Schnitstelle installiert. Aufruf der Aktionen sollte so aussehen - domain.tld/DeltraShopConnector/setArticles. Dabei sollte function setArticlesAction in engine\Shopware\Plugins\Community\Frontend\DeltraShopConnector\Controllers\Frontend\DeltraShopConnector.php aufgerufen werden.  Leider es funktioniert mit nginx nicht - 404 Error (apache hat kein Problem). Wie kann man das korrigieren?

**Comment by andreaspollak** [comment]
Nur mal so als schnelle Lösung, schon mal versucht das so zu konfigurieren:
(Wobei "/recovery/install" durch den benötigten Pfad getauscht werden muss)

```
location /recovery/install {
    index index.php;	
    try_files $uri /recovery/install/index.php?$args;
}
```

**Comment by Kamik** [comment]
Danke für Vorschlag. Sollte es so aussehen:

location /DeltraShopConnector/ {
    index DeltraShopConnector.php;    
    try_files $uri /engine\Shopware\Plugins\Community\Frontend\DeltraShopConnector\Controllers\Frontend\DeltraShopConnector.php?$args;
}

**Comment by andreaspollak** [comment]
Gerne! Ja, genau. Wobei der Pfad noch falsch ist, hier die Korrektur.

location /DeltraShopConnector/ {
	#index DeltraShopConnector.php;
	try_files $uri /engine/Shopware/Plugins/Community/Frontend/DeltraShopConnector/Controllers/Frontend/DeltraShopConnector.php?$args;
}

Einfach mal herantasten.

**Comment by Kamik** [comment]
Oh, es ist kein Problem mit nginx, sorry. In dem Plugin steht die Prüfung ob  USER_AGENT gleich Benutzername ist. Nach dem ich USER_AGENT geändert habe, funktioniert mit der Standardkonfiguration. Danke für die Hilfe, Andreas.

**Comment by andreaspollak** [comment]
Kein Problem, gerne!
Danke für die Rückinfo, vielleicht hilft es ja auch dem nächsten der darüber stolpert.
Beste Grüße
Andreas
