### ISSUE TITLE
Updates are not possible ...

### ISSUE THREAD

**Issue by ChrisGitIt** [bcremer/shopware-with-nginx#24]
Hi all,

with this config, i'm not able to update Shopware.

I tried to reproduce this problem with a clean and fresh install (v 5.1.6) and want to update to 5.2.6 (also tried a while ago to update to 5.2.1).

The update stops at http://domain.com/recovery/update/index.php/dbmigration
Showing:

> Error
> Received an error message.
> URL: unpack?offset=0&total=0
> Message: Not Found
> 
> Please try to fix this error and restart the update.
> Response
> 404 Page Not Found
> The page you are looking for could not be found. Check the address bar to ensure your URL is spelled correctly. If all else fails, you can visit our home page at the link below.

I think its because the nginx config does not take the following URLs into account:
http://domain.com/recovery/update/index.php/unpack?offset=0&total=0

I tried to change the jquery update script to get URLs like this (removed the "index.php"):
http://domain.com/recovery/update/unpack?offset=0&total=0

But this also does not work. I think its because the PHP Update Script uses app.map("/unpack").

I also tried several nginx changes but none of them works. Any help is greatly appreciate!

Greets,

Chris

**Comment by Gargamil** [comment]
+1

**Comment by ChrisGitIt** [comment]
Hi Gargamil,

i think it helps a lot to replace:
```
location /recovery/update {
    index index.php;
    try_files $uri /recovery/update/index.php?$is_args$args;
}
```
with:

```
location /recovery/update/ {
                location /recovery/update/assets {
                }
                if (!-e $request_filename){
                        rewrite . /recovery/update/index.php last;
                }
}
```
i found this somewhere along the internet and it solves my issue, but i'm not sure why there is a difference ...

**Comment by Gargamil** [comment]
Yes, found this too and it works!
Maybe the config should be updated..

**Comment by lhwparis** [comment]
+1

**Comment by kayyyy** [comment]
@ChrisGitIt Yeah that did the trick for me.
