### ISSUE TITLE
Configurable php-fpm upstream

### ISSUE THREAD

**Issue by emilv** [bcremer/shopware-with-nginx#29]
`global/shopware.conf` is brilliant. Worked much better than my first attempt at a Shopware snippet!

We would prefer to have different PHP-FPM upstreams for different servers. I implemented this on our server by changing fastcgi_pass to:

    fastcgi_pass $fpm_upstream;

and in the `server { ... }` block setting the variable along with the environment key:

    set $fpm_upstream php-staging;
    set $shopware_env 'staging';

**Comment by bcremer** [comment]
@emilv Great addition, thanks for the PR :+1:
