### ISSUE TITLE
Item export (Produktexporte) feeds return 404 error

### ISSUE THREAD

**Issue by Kamik** [bcremer/shopware-with-nginx#35]
I have trouble witch Item export (Produktexporte) urls https://domain/backend/export/index/feed.xml
I get 404 error and redirect to backend. 
Can anyone confirm?

**Comment by Kamik** [comment]
So you have to remove xml from line 
`location` ~ * ^. + \. (?: css | cur | js | jpe? G | gif | ico | png | html | xml) $ {`
Should look like this
 `location ~ * ^. + \. (?: css | cur | js | jpe? G | gif | ico | png | html) $ {`

**Comment by emilv** [comment]
Yeah, that one was fixed in November: https://github.com/bcremer/shopware-with-nginx/pull/20
