### ISSUE TITLE
Subshops not working

### ISSUE THREAD

**Issue by loeffel-io** [bcremer/shopware-with-nginx#37]
Hey,
thank u very much for your work. It works good but the routing for the subshops is not working. 

For example: 
https://{domain}.com/{subpage} is working! 
https://{domain}.com/{subshop}/{subpage} is **not** working (e. g. https://{domain}.com/en/imprint). 

Do you have any ideas why this is not working? 

Thank u!

**Comment by bcremer** [comment]
Hi @loeffel-io, as I am no longer activly working on shopware I am unable to provide helpful answers here.
Maybe some of my former colleages can chime in.  @soebbing @janbuecker

**Comment by janbuecker** [comment]
@loeffel-io i'll have a look into it.
@bcremer do you mind if we fork this repository into shopwareLabs as there won't be much support in here?

**Comment by loeffel-io** [comment]
Thank you! Btw it's a ```404 error``` and the message is ```Controller de not found```. It's not working for any of these routes (de|en|..).

**Comment by soebbing** [comment]
Just to be sure: You defined the /de and /en prefix in the settings of each shop?

**Comment by bcremer** [comment]
@janbuecker As long as the author notice in https://github.com/bcremer/shopware-with-nginx/blob/master/global/shopware.conf#L1 is preserved this is totally fine for me.

**Comment by janbuecker** [comment]
Sure thing, I would even mention you in the `README.md` as original author.

**Comment by loeffel-io** [comment]
@soebbing Sure 👍

**Comment by loeffel-io** [comment]
@janbuecker do u have any updates? 🙂

**Comment by Hotte512** [comment]
@bcremer can you please work on shopware.. again? :-)
@janbuecker please fork it and make a small update ;-)

btw. is (some)there an information about nginx/shopware and payment providers?
dose it work fine with let's say Heidelpay, PayPal, Stripe, Klarna ?

**Comment by emilv** [comment]
@Hotte512 As long as the payment providers hook into the Shopware system the right way they should all work fine. We use the Adyen provider from Customweb and it works out of the box on Nginx.

**Comment by marove2000** [comment]
@janbuecker are there any news on how to configure nginx for sub shops? :)

**Comment by loeffel-io** [comment]
Hey, this config works great for the Subshops. It was a SSL problem. Sorry for that and thank you 👍

**Comment by bcremer** [comment]
@loeffel-io Glad to hear. Thanks for reporting back :)

**Comment by Isengo1989** [comment]
@loeffel-io what was the problem with de/en ? I am having trouble getting the request to work:

http://local.shop.ch/de/shopware.php?sViewport=detail&sArticle=49758&sCategory=8746

Normal call of the product (SEO URl works)

**Comment by loeffel-io** [comment]
@Isengo1989 Your full page isn't working for me

**Comment by Isengo1989** [comment]
Tried that already - did not work. I switched to Apache for now. Does it work in your Environment?
